"""Project configuration and feature definitions."""

from __future__ import annotations

FEATURES_NUMERIC = [
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
    "DAYS_EMPLOYED",
    "DAYS_BIRTH",
    "DAYS_REGISTRATION",
]

FEATURES_CATEGORICAL = [
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
]

RATIO_FEATURES = {
    "RATIO_CREDIT_INCOME": ("AMT_CREDIT", "AMT_INCOME_TOTAL"),
    "RATIO_ANNUITY_INCOME": ("AMT_ANNUITY", "AMT_INCOME_TOTAL"),
}

KNOWN_ANOMALY_COLUMN = "DAYS_EMPLOYED"
KNOWN_ANOMALY_VALUE = 365243
